
select * from tbArea
select * from tbCargoTrabajador
select * from tbDespacha
select * from tbkardex
select * from tbPais
select * from tbPedidoProducto
select * from tbPermisos
select * from tbPersona
select * from tbProducto
select * from tbProfesion
select * from tbproveedor
select * from tbRoles
select * from tbSuministra
select * from tbTipoProducto
select * from tbTipoUsuario
select * from tbTrabajador
select * from tbTurno
select * from tbUbicacion
select * from tbUnidadMedida
select * from tbVendedorProveedor

delete from tbpais

insert into tbPais values ('1A'  ,'CHECOSLOVAQUIA')
insert into tbPais values ('1B'  ,'ZONAS FRANCAS DEL PERU')
insert into tbPais values ('1C'  ,'PAISES NO PREC. EN OP. ABAST. COMBUST')
insert into tbPais values ('1D'  ,'AGUAS INTERNACIONALES')
insert into tbPais values ('1E'  ,'NO DECLARADOS')
insert into tbPais values ('1F'  ,'GAZA Y JERICO')
insert into tbPais values ('1G'  ,'ESCOCIA')
insert into tbPais values ('1H'  ,'URSS')
insert into tbPais values ('1I'  ,'VIETNAM (DEL NORTE)')
insert into tbPais values ('1J'  ,'COMUNIDAD ECONOMICA EUROPEA')
insert into tbPais values ('1K'  ,'COSTA DE MARFIL')
insert into tbPais values ('1L'  ,'ZONA DEL CANAL DE PANAMA')
insert into tbPais values ('1M'  ,'ALEMANIA')
insert into tbPais values ('1N'  ,'ISLAS NORMANDAS')
insert into tbPais values ('1O'  ,'CANTON Y ENDERBURRY')
insert into tbPais values ('1P'  ,'HONDURAS BRITANICAS')
insert into tbPais values ('1Q'  ,'ISALAS JONSTON')
insert into tbPais values ('1R'  ,'MACEDONIA')
insert into tbPais values ('1S'  ,'MIDWAY, ISLAS')
insert into tbPais values ('1T'  ,'ISLAS DE PACIFICO')
insert into tbPais values ('1U'  ,'REPUBLICA ARABE UNIDA')
insert into tbPais values ('1V'  ,'WAKE, ISLA')
insert into tbPais values ('1W'  ,'TERRITORIO AUTONOMO DE PALESTINA.')
insert into tbPais values ('99'  ,'TODOS LOS PAISES')
insert into tbPais values ('AD'  ,'ANDORRA')
insert into tbPais values ('AE'  ,'EMIRATOS ÁRABES UNIDOS')
insert into tbPais values ('AF'  ,'AFGANISTÁN')
insert into tbPais values ('AG'  ,'ANTIGUA Y BARBUDA')
insert into tbPais values ('AI'  ,'ANGUILA')
insert into tbPais values ('AL'  ,'ALBANIA')
insert into tbPais values ('AM'  ,'ARMENIA')
insert into tbPais values ('AN'  ,'ANTILLAS HOLANDESAS')
insert into tbPais values ('AO'  ,'ANGOLA')
insert into tbPais values ('AQ'  ,'ANTÁRTIDA')
insert into tbPais values ('AR'  ,'ARGENTINA')
insert into tbPais values ('AS'  ,'SAMOA AMERICANA')
insert into tbPais values ('AT'  ,'AUSTRIA')
insert into tbPais values ('AU'  ,'AUSTRALIA')
insert into tbPais values ('AW'  ,'ARUBA')
insert into tbPais values ('AX'  ,'ISLAS ALAND')
insert into tbPais values ('AZ'  ,'AZERBAIJAN')
insert into tbPais values ('BA'  ,'BOSNIA Y HERZEGOVINA')
insert into tbPais values ('BB'  ,'BARBADOS')
insert into tbPais values ('BD'  ,'BANGLADESH')
insert into tbPais values ('BE'  ,'BÉLGICA')
insert into tbPais values ('BF'  ,'BURKINA FASO')
insert into tbPais values ('BG'  ,'BULGARIA')
insert into tbPais values ('BH'  ,'BAHREIN')
insert into tbPais values ('BI'  ,'BURUNDI')
insert into tbPais values ('BJ'  ,'BENIN')
insert into tbPais values ('BL'  ,'SANTA BARTHELEMY')
insert into tbPais values ('BM'  ,'ISLAS BERMUDAS')
insert into tbPais values ('BN'  ,'BRUNEI DARUSSALAM')
insert into tbPais values ('BO'  ,'BOLIVIA')
insert into tbPais values ('BQ'  ,'BONAIRE')
insert into tbPais values ('BR'  ,'BRASIL')
insert into tbPais values ('BS'  ,'BAHAMAS')
insert into tbPais values ('BT'  ,'BHUTAN')
insert into tbPais values ('BV'  ,'ISLA DE BOUVET')
insert into tbPais values ('BW'  ,'BOTSWANA')
insert into tbPais values ('BY'  ,'BELARUS')
insert into tbPais values ('BZ'  ,'BELICE')
insert into tbPais values ('CA'  ,'CANADÁ')
insert into tbPais values ('CC'  ,'COCOS (KEELING) ISLAS')
insert into tbPais values ('CD'  ,'CONGO LA REPÚBLICA DEMOCRÁTICA DE LA')
insert into tbPais values ('CF'  ,'REPÚBLICA CENTROAFRICANA')
insert into tbPais values ('CG'  ,'CONGO')
insert into tbPais values ('CH'  ,'SUIZA')
insert into tbPais values ('CI'  ,'COTE IVOIRE')
insert into tbPais values ('CK'  ,'ISLAS COOK')
insert into tbPais values ('CL'  ,'CHILE')
insert into tbPais values ('CM'  ,'CAMERÚN')
insert into tbPais values ('CN'  ,'CHINA')
insert into tbPais values ('CO'  ,'COLOMBIA')
insert into tbPais values ('CR'  ,'COSTA RICA')
insert into tbPais values ('CS'  ,'SERBIA Y MONTENEGRO')
insert into tbPais values ('CU'  ,'CUBA')
insert into tbPais values ('CV'  ,'CABO VERDE')
insert into tbPais values ('CW'  ,'CURAZAO')
insert into tbPais values ('CX'  ,'ISLA DE NAVIDAD')
insert into tbPais values ('CY'  ,'CHIPRE')
insert into tbPais values ('CZ'  ,'REPUBLICA CHECA')
insert into tbPais values ('DE'  ,'ALEMANIA')
insert into tbPais values ('DJ'  ,'DJIBOUTI')
insert into tbPais values ('DK'  ,'DINAMARCA')
insert into tbPais values ('DM'  ,'DOMINICA')
insert into tbPais values ('DO'  ,'REPÚBLICA DOMINICANA')
insert into tbPais values ('DZ'  ,'ARGELIA')
insert into tbPais values ('EC'  ,'ECUADOR')
insert into tbPais values ('EE'  ,'ESTONIA')
insert into tbPais values ('EG'  ,'EGIPTO')
insert into tbPais values ('EH'  ,'SAHARA OCCIDENTAL')
insert into tbPais values ('ER'  ,'ERITREA')
insert into tbPais values ('ES'  ,'ESPAÑA')
insert into tbPais values ('ET'  ,'ETIOPÍA')
insert into tbPais values ('FI'  ,'FINLANDIA')
insert into tbPais values ('FJ'  ,'FIJI')
insert into tbPais values ('FK'  ,'ISLAS MALVINAS (MALVINAS)')
insert into tbPais values ('FM'  ,'MICRONESIA, ESTADOS FEDERADOS DE')
insert into tbPais values ('FO'  ,'ISLAS FAROE')
insert into tbPais values ('FR'  ,'FRANCIA')
insert into tbPais values ('FX'  ,'FRANCIA, METROPOLITANO')
insert into tbPais values ('GA'  ,'GABÓN')
insert into tbPais values ('GB'  ,'REINO UNIDO')
insert into tbPais values ('GD'  ,'GRANADA')
insert into tbPais values ('GE'  ,'GEORGIA')
insert into tbPais values ('GF'  ,'GUIANA FRANCESA')
insert into tbPais values ('GG'  ,'GUERNSEY')
insert into tbPais values ('GH'  ,'GHANA')
insert into tbPais values ('GI'  ,'GIBRALTAR')
insert into tbPais values ('GL'  ,'TIERRA VERDE')
insert into tbPais values ('GM'  ,'GAMBIA')
insert into tbPais values ('GN'  ,'GUINEA')
insert into tbPais values ('GP'  ,'GUADALUPE')
insert into tbPais values ('GQ'  ,'GUINEA ECUATORIAL')
insert into tbPais values ('GR'  ,'GRECIA')
insert into tbPais values ('GS'  ,'GEORGIA DEL SUR Y LAS ISLAS SANDWICH DEL')
insert into tbPais values ('GT'  ,'GUATEMALA')
insert into tbPais values ('GU'  ,'GUAM')
insert into tbPais values ('GW'  ,'GUINEA-BISSAU')
insert into tbPais values ('GY'  ,'GUAYANA')
insert into tbPais values ('HK'  ,'HONG KONG')
insert into tbPais values ('HM'  ,'ISLA DEL OÍDO Y LAS ISLAS MDDALLD')
insert into tbPais values ('HN'  ,'HONDURAS')
insert into tbPais values ('HR'  ,'CROACIA')
insert into tbPais values ('HT'  ,'HAITÍ')
insert into tbPais values ('HU'  ,'HUNGRÍA')
insert into tbPais values ('ID'  ,'INDONESIA')
insert into tbPais values ('IE'  ,'IRLANDA')
insert into tbPais values ('IL'  ,'ISRAEL')
insert into tbPais values ('IM'  ,'ISLA DEL HOMBRE')
insert into tbPais values ('IN'  ,'INDIA')
insert into tbPais values ('IO'  ,'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO')
insert into tbPais values ('IQ'  ,'IRAK')
insert into tbPais values ('IR'  ,'IRÁN (REPÚBLICA ISLÁMICA DE')
insert into tbPais values ('IS'  ,'ISLANDIA')
insert into tbPais values ('IT'  ,'ITALIA')
insert into tbPais values ('JE'  ,'JERSEY')
insert into tbPais values ('JM'  ,'JAMAICA')
insert into tbPais values ('JO'  ,'JORDÁN')
insert into tbPais values ('JP'  ,'JAPÓN')
insert into tbPais values ('KE'  ,'KENIA')
insert into tbPais values ('KG'  ,'KYRGYZSTAN')
insert into tbPais values ('KH'  ,'CAMBOYA')
insert into tbPais values ('KI'  ,'KIRIBATI')
insert into tbPais values ('KM'  ,'COMORES')
insert into tbPais values ('KN'  ,'SAINT KITTS Y NEVIS')
insert into tbPais values ('KP'  ,'COREA, REP. DE LAS PERSONAS DEMOCRATICAS')
insert into tbPais values ('KR'  ,'COREA, REPÚBLICA DE')
insert into tbPais values ('KW'  ,'KUWAIT')
insert into tbPais values ('KY'  ,'ISLAS CAIMÁN')
insert into tbPais values ('KZ'  ,'KAZAJSTÁN')
insert into tbPais values ('LA'  ,'REPÚBLICA DEMOCRÁTICA POPULAR DE LAO')
insert into tbPais values ('LB'  ,'LÍBANO')
insert into tbPais values ('LC'  ,'SANTA LUCÍA')
insert into tbPais values ('LI'  ,'LIECHTENSTEIN')
insert into tbPais values ('LK'  ,'SRI LANKA')
insert into tbPais values ('LR'  ,'LIBERIA')
insert into tbPais values ('LS'  ,'LESOTO')
insert into tbPais values ('LT'  ,'LITUANIA')
insert into tbPais values ('LU'  ,'LUXEMBURGO')
insert into tbPais values ('LV'  ,'LETONIA')
insert into tbPais values ('LY'  ,'LIBIA')
insert into tbPais values ('MA'  ,'MARRUECOS')
insert into tbPais values ('MC'  ,'MÓNACO')
insert into tbPais values ('MD'  ,'MOLDAVIA, REPÚBLICA DE')
insert into tbPais values ('ME'  ,'MONTENEGRO')
insert into tbPais values ('MF'  ,'SAN MARTIN (PARTE FRANCESA)')
insert into tbPais values ('MG'  ,'MADAGASCAR')
insert into tbPais values ('MH'  ,'ISLAS MARSHALL')
insert into tbPais values ('MK'  ,'MACEDONIA, LA ANTIGUA REPÚBLICA YUGOSLAV')
insert into tbPais values ('ML'  ,'MALI')
insert into tbPais values ('MM'  ,'MYANMAR')
insert into tbPais values ('MN'  ,'MONGOLIA')
insert into tbPais values ('MO'  ,'MACAO')
insert into tbPais values ('MP'  ,'ISLAS MARIANAS DEL NORTE')
insert into tbPais values ('MQ'  ,'MARTINICA')
insert into tbPais values ('MR'  ,'MAURITANIA')
insert into tbPais values ('MS'  ,'MONTSERRAT')
insert into tbPais values ('MT'  ,'MALTA')
insert into tbPais values ('MU'  ,'MAURICIO')
insert into tbPais values ('MV'  ,'MALDIVAS')
insert into tbPais values ('MW'  ,'MALAWI')
insert into tbPais values ('MX'  ,'MEXICO')
insert into tbPais values ('MY'  ,'MALASIA')
insert into tbPais values ('MZ'  ,'MOZAMBIQUE')
insert into tbPais values ('NA'  ,'NAMIBIA')
insert into tbPais values ('NC'  ,'NUEVA CALEDONIA')
insert into tbPais values ('NE'  ,'NÍGER')
insert into tbPais values ('NF'  ,'ISLA NORFOLK')
insert into tbPais values ('NG'  ,'NIGERIA')
insert into tbPais values ('NI'  ,'NICARAGUA')
insert into tbPais values ('NL'  ,'PAÍSES BAJOS')
insert into tbPais values ('NO'  ,'NORUEGA')
insert into tbPais values ('NP'  ,'NEPAL')
insert into tbPais values ('NR'  ,'NAURU')
insert into tbPais values ('NT'  ,'ZONA NEUTRAL')
insert into tbPais values ('NU'  ,'NIUE')
insert into tbPais values ('NZ'  ,'NUEVA ZELANDA')
insert into tbPais values ('OM'  ,'OMÁN')
insert into tbPais values ('PA'  ,'PANAMÁ')
insert into tbPais values ('PE'  ,'PERÚ')
insert into tbPais values ('PF'  ,'POLINESIA FRANCÉS')
insert into tbPais values ('PG'  ,'PAPÚA NUEVA GUINEA')
insert into tbPais values ('PH'  ,'FILIPINAS')
insert into tbPais values ('PK'  ,'PAKISTÁN')
insert into tbPais values ('PL'  ,'POLONIA')
insert into tbPais values ('PM'  ,'SAN PIERRE Y MIQUELON')
insert into tbPais values ('PN'  ,'PITCAIRN')
insert into tbPais values ('PR'  ,'PUERTO RICO')
insert into tbPais values ('PS'  ,'PALESTINA, ESTADO DE')
insert into tbPais values ('PT'  ,'PORTUGAL')
insert into tbPais values ('PW'  ,'PALAU')
insert into tbPais values ('PY'  ,'PARAGUAY')
insert into tbPais values ('QA'  ,'KATAR')
insert into tbPais values ('RE'  ,'REUNIÓN')
insert into tbPais values ('RO'  ,'RUMANIA')
insert into tbPais values ('RS'  ,'SERBIA')
insert into tbPais values ('RU'  ,'FEDERACIÓN RUSA')
insert into tbPais values ('RW'  ,'RUANDA')
insert into tbPais values ('SA'  ,'ARABIA SAUDITA')
insert into tbPais values ('SB'  ,'ISLAS SALOMÓN')
insert into tbPais values ('SC'  ,'SEYCHELLES')
insert into tbPais values ('SD'  ,'SUDÁN')
insert into tbPais values ('SE'  ,'SUECIA')
insert into tbPais values ('SG'  ,'SINGAPUR')
insert into tbPais values ('SH'  ,'SANTA HELENA, ASCENSIÓN Y TRISTÁN DA CUN')
insert into tbPais values ('SI'  ,'ESLOVENIA')
insert into tbPais values ('SJ'  ,'SVALBARD Y JAN MAYEN')
insert into tbPais values ('SK'  ,'ESLOVAQUIA')
insert into tbPais values ('SL'  ,'SIERRA LEONA')
insert into tbPais values ('SM'  ,'SAN MARINO')
insert into tbPais values ('SN'  ,'SENEGAL')
insert into tbPais values ('SO'  ,'SOMALIA')
insert into tbPais values ('SR'  ,'SURINAME')
insert into tbPais values ('SS'  ,'SUDÁN DEL SUR')
insert into tbPais values ('ST'  ,'SANTO TOMÉ Y PRÍNCIPE')
insert into tbPais values ('SV'  ,'EL SALVADOR')
insert into tbPais values ('SX'  ,'SINT MAARTEN (PARTE HOLANDESA)')
insert into tbPais values ('SY'  ,'REPÚBLICA ÁRABE SIRIA')
insert into tbPais values ('SZ'  ,'SWAZILANDIA')
insert into tbPais values ('TC'  ,'ISLAS TURCAS Y CAICOS')
insert into tbPais values ('TD'  ,'CHAD')
insert into tbPais values ('TF'  ,'TERRITORIOS FRANCESES DEL SUR')
insert into tbPais values ('TG'  ,'TOGO')
insert into tbPais values ('TH'  ,'TAILANDIA')
insert into tbPais values ('TJ'  ,'TAYIKISTAN')
insert into tbPais values ('TK'  ,'TOKAELU')
insert into tbPais values ('TL'  ,'TIMOR-LESTE')
insert into tbPais values ('TM'  ,'TURKMENISTÁN')
insert into tbPais values ('TN'  ,'TÚNEZ')
insert into tbPais values ('TO'  ,'TONGA')
insert into tbPais values ('TP'  ,'TIMOR ORIENTAL')
insert into tbPais values ('TR'  ,'TURQUIA')
insert into tbPais values ('TT'  ,'TRINIDAD Y TOBAGO')
insert into tbPais values ('TV'  ,'TUVALU')
insert into tbPais values ('TW'  ,'TAIWAN, PROVINCIA DE CHINA')
insert into tbPais values ('TZ'  ,'TANZANIA, REPÚBLICA DE LOS ESTADOS UNIDO')
insert into tbPais values ('UA'  ,'UCRANIA')
insert into tbPais values ('UG'  ,'UGANDA')
insert into tbPais values ('UM'  ,'ISLAS MENORES DE LOS ESTADOS UNIDOS')
insert into tbPais values ('US'  ,'ESTADOS UNIDOS')
insert into tbPais values ('UY'  ,'URUGUAY')
insert into tbPais values ('UZ'  ,'UZBEKISTÁN')
insert into tbPais values ('VA'  ,'SANTA SEDE (ESTADO DE LA CIUDAD DEL VATI')
insert into tbPais values ('VC'  ,'SAN VICENTE Y LAS GRANADINAS')
insert into tbPais values ('VE'  ,'VENEZUELA')
insert into tbPais values ('VG'  ,'ISLAS VÍRGENES BRITÁNICAS')
insert into tbPais values ('VI'  ,'ISLAS VÍRGENES, EE. UU.')
insert into tbPais values ('VN'  ,'VIET NAM')
insert into tbPais values ('VU'  ,'VANUATU')
insert into tbPais values ('WF'  ,'WALLIS Y FUTUNA')
insert into tbPais values ('WS'  ,'SAMOA')
insert into tbPais values ('XX'  ,'PUEBA')
insert into tbPais values ('XZ'  ,'INSTALACIONES EN AGUA INTERNACIONAL')
insert into tbPais values ('YE'  ,'YEMEN')
insert into tbPais values ('YT'  ,'MAYOTTE')
insert into tbPais values ('YU'  ,'YUGOSLAVIA')
insert into tbPais values ('ZA'  ,'SUDÁFRICA')
insert into tbPais values ('ZM'  ,'ZAMBIA')
insert into tbPais values ('ZR'  ,'ZAIRE')
insert into tbPais values ('ZW'  ,'ZIMBABUE')

insert into tbPersona (idPais, perApellidos, perNombres, perFechaNac, perDNI, perEstado, perTelefono, perCorreo, perDireccion, perSexo) 
values ('PE','ZEVALLOS HIDALGO', 'KENNETH MIGUEL','01/01/1990','45170770','1','999999888','KZEVALLOS@GMAIL.COM.PE', 'AV CORONEL SIN NUMERO','1'), 
('US','CASTRO ROBLES', 'OSCAR','01/01/1990','45170770','1','514645445','ROBLES@GMAIL.COM.PE', 'AV CORONEL SIN NUMERO','1'),
('JP','KANASHIRO TANAKA', 'KEN','01/01/1990','45170770','1','79156423565','KENS@GMAIL.COM.PE', 'AV CORONEL SIN NUMERO','1')

SELECT * FROM tbSuministra
insert into tbSuministra (lote, cantidad, numFactura, paisOrigen, precio_compra) values ('15102021',100,'F001-00000001', 'PE',5.23)